// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYR2WAphoUFBaM9U1Q-NYk0Lzk__CjK0k',
    appId: '1:535239367221:web:6d5d4bf3668b3e17182f7c',
    messagingSenderId: '535239367221',
    projectId: 'rappproj',
    authDomain: 'rappproj.firebaseapp.com',
    storageBucket: 'rappproj.appspot.com',
    measurementId: 'G-LJRV9S7BX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2r9045VDRSD_r1pXnb4rvhsAReUQr3o',
    appId: '1:535239367221:android:a200a7f1be118fc3182f7c',
    messagingSenderId: '535239367221',
    projectId: 'rappproj',
    storageBucket: 'rappproj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzRwaNnGD4wRfbg4BipIa5lfliY_ZA37Y',
    appId: '1:535239367221:ios:9183c7463f77f780182f7c',
    messagingSenderId: '535239367221',
    projectId: 'rappproj',
    storageBucket: 'rappproj.appspot.com',
    iosBundleId: 'com.example.rappproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzRwaNnGD4wRfbg4BipIa5lfliY_ZA37Y',
    appId: '1:535239367221:ios:5164b156a4e7e843182f7c',
    messagingSenderId: '535239367221',
    projectId: 'rappproj',
    storageBucket: 'rappproj.appspot.com',
    iosBundleId: 'com.example.rappproj.RunnerTests',
  );
}
